{
 "title": "CPU here",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU usage (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m])",
     "legendFormat": "User CPU"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total[1m])",
     "legendFormat": "System CPU"
    }
   ]
  },
  {
   "title": "Resident memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Heap used" },
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Heap total" }
   ]
  },
  {
   "title": "Event loop lag (mean)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_mean_seconds",
     "legendFormat": "Lag nodejs"
    }
   ]
  }
 ]
}