services:

  core-api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: core-api
    environment:
      NODE_ENV: production
      DOCKER_ENV: 'true'
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      ALLOWED_ORIGINS: '${ALLOWED_ORIGINS:-https://localhost:8443}'
      DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-db}"
      JWT_SECRET: ${JWT_SECRET:-thisisasecret}
    depends_on:
      postgres:
       condition : service_healthy
    restart: unless-stopped
    networks:
      - postgres-network

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-db} -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - postgres-network

  prometheus:
    image: prom/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./back-end/prometheus:/etc/prometheus
      - prom-data:/prometheus
    networks:
      - postgres-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SERVER_HTTP_PORT : "3002"
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-SuperSecret123}
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./back-end/grafana/dashboards:/var/lib/grafana/dashboards
      - ./back-end/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - postgres-network

  socket-chat:
    build:
      context: ./back-end/websocket/
      dockerfile: Dockerfile
    container_name: socket-chat
    environment:
      WS_PORT: ${WS_HOST:-8090}
      JWT_SECRET: ${JWT_SECRET:-thisisasecret}
    restart: unless-stopped
    networks:
      - postgres-network

  nginx:
    build:
      context: ./back-end/nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "8443:8443"
      - "8080:8080"
    volumes:
      - ./back-end/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./back-end/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - core-api
      - socket-chat
    networks:
      - postgres-network
    restart: unless-stopped

  transcendence:
    build:
      context: ./front-end/
      dockerfile: Dockerfile
      target: production
    container_name: transcendence-front
    #    ports:
     # - '${PORT:-8080}:8080'
    environment:
      NODE_ENV: production
      DOCKER_ENV: 'true'
    restart: unless-stopped
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
  prom-data: {}
  grafana-storage: {}
