services:

  socket-chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socket-chat
    ports:
      - '${WS_PORT:-8090}:8090' # API server
    environment:
      WS_PORT: ${WS_HOST:-8090}
      JWT_SECRET: "4X1fdYDG8LGBURWxT042Jqr9XZqKP4F4JqbVE+moI5Ly3iU/wCUQbS8ei3KRcG0XQtrO0gngbrCitl35R9ERrw=="
      # ${JWT_SECRET:-thisisasecret}
    restart: unless-stopped
